---
- hosts: localhost
  vars:
    description: "auth users"
    create_data: 
        clientId: "openshift"
        name:     "OpenShift"
        description: "OpenShift Console Authentication"
        enabled: true
        protocol: "openid-connect"
        clientAuthenticatorType: "client-secret"
        directAccessGrantsEnabled: true
        redirectUris: ["https://gsw1v36.southeastasia.cloudapp.azure.com:8443"]
        webOrigins: []
        publicClient: false
        consentRequired: false
        frontchannelLogout: false
        standardFlowEnabled: true
    
  tasks:
  - name: Login to SSO
    uri:
      url: https://login.52.160.91.126.nip.io/auth/realms/cloud/protocol/openid-connect/token
      method: POST
      body: "grant_type=password&client_id=admin-cli&username=sso-mgmtuser&password=mgmt-password"
      return_content: yes
      status_code: 200
      validate_certs: no
    register: login
  - debug: var=login.json.access_token
  - name: Login to SSO
    uri:
      url: https://login.52.160.91.126.nip.io/auth/realms/cloud/clients-registrations/default
      method: POST
      headers: 
           "Authorization": "bearer {{login.json.access_token}}"
           "Content-Type": "application/json"
      body: "{{ create_data | to_json }}"
      return_content: yes
      status_code: 201
      validate_certs: no
    register: create
  - debug: var=create.json.secret

